spring:
    datasource:
        url: jdbc:mysql://localhost:3306/thoughtfocus
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: Avian@9483
    jpa:
        hibernate:
            ddl-auto: update
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    
#logging:
    #level:
        #com:
            #thoughtfocus: DEBUG
    #pattern:
        #console: "%{yyyy-mm-dd} - %m %n"
